!===========================  INTGPAW   U8 =============================
!        INTGPAW constructs constraints from the logderiv.* file      >>
!--------------------------------------------------------------------->>
!   VARIABLES/  |                      DESCRIPTION OF                 >>
!   PARAMETERS  |                   VARIABLES/PARAMETERS              >>
!.....................................................................>>
!nlgfl          : # of logderiv.* files generated by atompaw program  >>
!n              : No. of lines in each logderiv.* files               >>
!dlgotm         : [sum of the difference between each point in the    >>
!                 log derivative plots of AE & ATOMPAW ] :absolute    >>
!dlga           : [difference between area of the log derivative      >>
!                 plots of AE & ATOMPAW ]^2                           >>
      SUBROUTINE INTGPAW(n,nlgfl,dlgotm,dlga)!                        >>
      IMPLICIT NONE!                                                  >>
      INTEGER i,j,n,ifl,nlgfl!                                        >>
      DOUBLE PRECISION s0(nlgfl,n),gr0(nlgfl,n),sr0(nlgfl,n)!         >>
      DOUBLE PRECISION s(n),gr(n),sr(n)!                              >>
      DOUBLE PRECISION summ,dlgotm,dlga,areagr,areasr!                >>
      CHARACTER*10 cna!                                               >>
!=======================================================================
! OPEN THE logderiv.* FILES
      do i=0,nlgfl-1
        ifl=9+i
        if(i.lt.10)then
          write(cna,FMT="(I1)")i
        elseif(i.lt.100)then
          write(cna,FMT="(I2)")i
        endif
        open(ifl,file='logderiv.'//trim(cna),status='unknown')
      enddo
! READ logderiv.* FILES & SUM OF THE DIFFERENCE BETWEEN EACH POINT
! ONTO MAPPING
      dlgotm=0.0d0
      do j=1,nlgfl
        summ=0.0d0
        ifl=8+j
        do i=1,n
          read(ifl,*)s0(j,i),gr0(j,i),sr0(j,i)
          if(dabs(gr0(j,i)).lt.5.0d0.and.dabs(sr0(j,i)).lt.5.0d0)then
             summ=summ+dabs(gr0(j,i)-sr0(j,i))
          endif
        enddo
        dlgotm=dlgotm+summ
      enddo
! SUM OF THE DIFFERENCE BETWEEN AREA UNDER THE CURVES
      dlga=0.0d0
      do j=1,nlgfl
        summ=0.0d0
        do i=1,n
          s(i)=s0(j,i)
          gr(i)=gr0(j,i)
          sr(i)=sr0(j,i)
        enddo
        call C_SIMPS(n,s,gr,areagr)
        call C_SIMPS(n,s,sr,areasr)
        summ=(areagr-areasr)*(areagr-areasr)
        dlga=dlga+summ
      enddo
      do i=0,nlgfl-1
        ifl=9+i
        close(ifl)
      enddo
      return
      end
